install-json-path: https://raw.githubusercontent.com/folio-org/platform-complete/snapshot/install.json
# Example local reference for linux: /home/user/projects/folio/busybee/platform-complete/install.json
additional-json-path: C:\Users\User\.busybee\additional_modules.json # Optional Read "How to run consortia" section in Busybee Tips Tricks
# A file path to your additional json file that can be used to deploy additional modules not usually included in install.json
# Example additional_modules.json:
#   [ { "id" : "mod-consortia-1.2.0-SNAPSHOT", "action" : "enable" } ]
# additional-json-path: /home/user/.busybee/additional_modules.json (linux)

## Copy modules in your .busybee/config.yml file
be-modules: # list the FOLIO backend modules you would like to spin up. Use CORE and END CORE modules for fast setup
  ## CORE: ensure that core FOLIO modules are first on this list
  - mod-permissions
  - mod-configuration
  - mod-login
  - mod-users
  - mod-users-bl
  - mod-authtoken
  ## END CORE
  - mod-source-record-manager
  - mod-source-record-storage
  - mod-inventory
  - mod-inventory-storage
  - mod-organizations
  - mod-organizations-storage
  - mod-entities-links
  - mod-invoice
  - mod-invoice-storage
  - mod-orders
  - mod-orders-storage
  - mod-pubsub
  - mod-tags
  - mod-finance
  - mod-finance-storage
  - mod-circulation-storage
  - mod-circulation
  - mod-audit
  - mod-template-engine
  - mod-feesfines
  ## Consortia (Optional). Read more about How to run consortia section in Busybee Tips Tricks
  - mod-consortia # add this module to install.json file or specify module in additional-json-path.
  - mod-password-validator
  ## Other modules (Optional)
  - edge-orders
  - mod-ebsconet
  - mod-gobi
  - mod-agreements

ui-modules:
  - folio_users
  - folio_data-import
  - folio_tenant-settings
  - folio_organizations
  - folio_inventory
  - folio_invoice
  - folio_orders
  - folio_finance
  - folio_receiving
  ## Consortia Settings UI (Optional)
  - folio_consortia_settings
  ## Other modules (Optional)
  - folio_acquisition-units
  - folio_developer